version: "3.0"
services:
  nginx:
    image: 872475949043.dkr.ecr.ap-northeast-1.amazonaws.com/fishing:nginx
    container_name: nginx
    ports:
      - "0:80"
    networks:
      ecs-network:
        ipv4_addredd: 10.0.0.1
  server:
    build: ./laravel
    container_name: laravel
    image: 872475949043.dkr.ecr.ap-northeast-1.amazonaws.com/fishing:latest
    ports:
     - "0:80"
    networks:
      ecs-network:
        ipv4_addredd: 10.0.0.0
  
    networks:
    ecs-network:
      driver: bridge
      ipam:
        driver: default
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/nginx-task
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs

