version: "3.0"
services:
  app:
    image: 872475949043.dkr.ecr.ap-northeast-1.amazonaws.com/fishing:nginx
    container_name: nginx-container
    ports:
      - "0:80"
    networks:
      - bridge
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/nginx-task
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs