version: "3.0"
services:
  app:
    image: 872475949043.dkr.ecr.ap-northeast-1.amazonaws.com/fishing:latest
    container_name: laravel
    ports:
      - "0:80"
    networks:
      ecs-network:
        ipv4_address: 10.0.0.0

    networks:
    ecs-network:
      driver: bridge
      ipam:
        driver: default
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/fishing-task
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs