version: "3.0"
volumes:
  php-fpm-socket:
services:
  app:
    image: 872475949043.dkr.ecr.ap-northeast-1.amazonaws.com/tsurins-app:latest
    env_file:
      - ./.env.production
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    container_name: laravel
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs/tsurins-app
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
        
  nginx:
    image: 872475949043.dkr.ecr.ap-northeast-1.amazonaws.com/tsurins-nginx:latest
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    container_name: nginx
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs/tsurins-nginx
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs

networks:
  ecs-network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: subnet-07bdd7d22859f3258