version: "3.0"
volumes:
  php-fpm-socket:
services:
  app:
    image: 872475949043.dkr.ecr.ap-northeast-1.amazonaws.com/fishing:latest
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    container_name: laravel
    ports:
      - "0:80"
    networks:
      ecs-network:
        ipv4_address: 172.17.0.3/16
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/fishing-task
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
        
  nginx:
    image: 872475949043.dkr.ecr.ap-northeast-1.amazonaws.com/fishing:nginx
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    container_name: nginx
    ports:
      - "0:80"
    networks:
      ecs-network:
        ipv4_address: 172.17.0.2/16
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/nginx-task
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs

networks:
  ecs-network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: subnet-059caa4e3fcb5985e