version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecs: circleci/aws-ecs@0.0.10

jobs: 
  build: 
    docker: 
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7

    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/fishing-docker

    steps: 
      - checkout 
      - run: pwd
      - run: cd ./laravel | ls -la
      - run: sudo apt install -y git libicu-dev libonig-dev libzip-dev unzip locales
      - run: sudo apt-get install default-mysql-server
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update
      - aws-cli/install
      - setup_remote_docker
      - aws-cli/configure:
          aws-access-key-id: ${aws_access_key_id}
          aws-secret-access-key: ${aws_secret_access_key}
          aws-region: ap-northeast-1          
      - run: aws sts get-caller-identity
      - run:
          name: setup ecs-cli
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
            ecs-cli --version
            ecs-cli configure profile --profile-name ecs-cli --access-key ${aws_access_key_id} --secret-key ${aws_secret_access_key}
            ecs-cli configure --cluster fishing-cluster --default-launch-type EC2 --region ap-northeast-1
      - run:
          name: cp .env
          working_directory: ~/fishing-docker/laravel
          command: cp .env.example .env
      - run:
          name: setup .env
          working_directory: ~/fishing-docker/laravel
          command: echo ${env_file} | base64 --decode > .env
      - run:
          name: sh
          working_directory: ~/fishing-docker/laravel
          command: sh aws.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature/deploy
        