version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4

executors:
  laravel-images: 
    working_directory: ~/fishing-docker
    docker: 
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7

    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD: true

jobs:
  build:
    executor: laravel-images
    steps: 
      - checkout 
      - run: sudo apt install -y git libicu-dev libonig-dev libzip-dev unzip locales
      - run: sudo apt-get install default-mysql-server
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update
      - run: composer install --working-dir=./laravel
      - run: 
          name: npm install
          working_directory: ~/fishing-docker/laravel
          command: npm install
      - run: 
          name: npm run dev
          working_directory: ~/fishing-docker/laravel
          command: npm run dev
      - run: 
          name: yarn install
          working_directory: ~/fishing-docker/laravel
          command: yarn install 
      - run: 
          name: .env
          working_directory: ~/fishing-docker/laravel
          command: cp .env.example .env 
      - run: 
          name: seed data
          working_directory: ~/fishing-docker/laravel
          command: php artisan migrate --seed
      - run: 
          name: app_key
          working_directory: ~/fishing-docker/laravel
          command: php artisan key:generate
      - run: 
          name: config:clear
          working_directory: ~/fishing-docker/laravel
          command: php artisan config:cache
      - run: 
          name: test
          working_directory: ~/fishing-docker/laravel
          command: ./vendor/bin/phpunit

  deploy:
    executor: laravel-images
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo composer self-update
      - run: composer install --working-dir=./laravel
      - run: 
          name: npm install
          working_directory: ~/fishing-docker/laravel
          command: npm install
      - run: 
          name: npm run dev
          working_directory: ~/fishing-docker/laravel
          command: npm run dev
      - run: 
          name: yarn install
          working_directory: ~/fishing-docker/laravel
          command: yarn install 
      - setup_remote_docker
      - aws-cli/configure:
          aws-access-key-id: ${aws_access_key_id}
          aws-secret-access-key: ${aws_secret_access_key}
          aws-region: ap-northeast-1
      - aws-cli/install        
      - run: aws sts get-caller-identity
      - run:
          name: setup ecs-cli
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
            ecs-cli --version
            ecs-cli configure profile --profile-name default --access-key ${aws_access_key_id} --secret-key ${aws_secret_access_key}
            ecs-cli configure --cluster tsurins-cluster --default-launch-type EC2 --region ap-northeast-1
      - run:
          name: cp .env
          working_directory: ~/fishing-docker/laravel
          command: cp .env.example .env
      - run:
          name: setup .env
          working_directory: ~/fishing-docker/laravel
          command: echo ${env_file} | base64 --decode > .env
      - run:
          name: permission change
          working_directory: ~/fishing-docker/laravel
          command: sudo chmod -R 777 ./storage
      - run:
          name: clear view
          working_directory: ~/fishing-docker/laravel
          command: php artisan view:clear
      - run: aws configure list --profile default
      - run: cat ~/fishing-docker/laravel/aws.sh
      - run:
          name: aws deploy file
          working_directory: ~/fishing-docker/laravel
          command: sh aws.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

        