version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecs: circleci/aws-ecs@0.0.10

jobs: 
executors:
  build: 
    docker: 
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7

    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/fishing-docker

    steps: 
      - checkout 
      - run: pwd
      - run: sudo apt install -y git libicu-dev libonig-dev libzip-dev unzip locales
      - run: sudo apt-get install default-mysql-server
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update
      - restore_cache: 
          keys:
            - composer-v1-{{ checksum "./laravel/composer.lock" }}
            # 正確な一致が見つからない場合は、最新のキャッシュの使用にフォールバックします (https://circleci.com/docs/ja/2.0/caching/ を参照)
            - composer-v1-
          paths: 
            - ./laravel
      - run: composer install -n --prefer-dist --working-dir=./laravel
      - save_cache: 
          key: composer-v1-{{ checksum "./laravel/composer.lock" }}
          paths:
            - ./laravel
      - restore_cache:
          keys:
            - node-v1-{{ checksum "./laravel/package-lock.json" }}
            # 正確な一致が見つからない場合は、最新のキャッシュの使用にフォールバックします (https://circleci.com/docs/ja/2.0/caching/ を参照)
            - node-v1-
          paths: 
            - ./laravel
      - run: yarn install 
      - save_cache: 
          key: node-v1-{{ checksum "./laravel/package-lock.json" }}
          paths:
            - ./laravel
      - run: 
          name: .env
          working_directory: ~/fishing-docker/laravel
          command: cp .env.example .env          
      - run: 
          name: seed data
          working_directory: ~/fishing-docker/laravel
          command: php artisan migrate --seed
      - run: 
          name: app_key
          working_directory: ~/fishing-docker/laravel
          command: php artisan key:generate
      - run: 
          name: config:clear
          working_directory: ~/fishing-docker/laravel
          command: php artisan config:cache
      - run: 
          name: test
          working_directory: ~/fishing-docker/laravel
          command: ./vendor/bin/phpunit

  deploy:
    exector:
      name: build
    steps:
      - run: pwd
      - run: cd ./laravel && ls -la

      - aws-cli/install
      - setup_remote_docker
      - aws-cli/configure:
          aws-access-key-id: ${aws_access_key_id}
          aws-secret-access-key: ${aws_secret_access_key}
          aws-region: ap-northeast-1          
      - run: aws sts get-caller-identity
      - run:
          name: setup ecs-cli
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
            ecs-cli --version
            ecs-cli configure profile --profile-name ecs-cli --access-key ${aws_access_key_id} --secret-key ${aws_secret_access_key}
            ecs-cli configure --cluster fishing-cluster --default-launch-type EC2 --region ap-northeast-1
      - run:
          name: cp .env
          working_directory: ~/fishing-docker/laravel
          command: cp .env.example .env
      - run:
          name: setup .env
          working_directory: ~/fishing-docker/laravel
          command: echo ${env_file} | base64 --decode > .env
      - run:
          name: sh
          working_directory: ~/fishing-docker/laravel
          command: sh aws.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature/deploy
        