version: 2.1
jobs:
  terraform:
    working_directory: ~/fishing-docker
    docker:
      - image: hashicorp/terraform:0.12.26
    steps:
      - checkout
      - run: terraform init
      - run: terraform plan

workflows:
  version: 2
  terraform plan:
    jobs:
      - terraform