version: 2.1
executors:
  terraform:
    working_directory: ~/fishing-docker
    docker:
      - image: hashicorp/terraform:0.12.26
      - image: circleci/python:3.7.3

jobs:
  terraform_plan:
    executor: terraform
    steps:
      - checkout
      - run: apk --update add curl
      - run: apk add py-pip
      - run: pip install awscli
      - run: aws configure set --profile Administrator aws_access_key_id ${aws_access_key_id} 
      - run: aws configure set --profile Administrator aws_secret_access_key ${aws_secret_access_key}
      - run: terraform init
      - run: terraform plan
    
  terraform_apply:
    executor: terraform
    steps:
      - checkout
      - run: apk --update add curl
      - run: apk add py-pip
      - run: pip install awscli
      - run: aws configure set --profile Administrator aws_access_key_id ${aws_access_key_id} 
      - run: aws configure set --profile Administrator aws_secret_access_key ${aws_secret_access_key}
      - run: terraform init
      - run: terraform apply -auto-approve

workflows:
  version: 2
  terraform_plan_and_apply:
    jobs:
      - terraform_plan
      - terraform_apply:
          requires:
            - terraform_plan
          filters:
            branches:
              only: terraform/production
