version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
jobs:
  terraform:
    working_directory: ~/fishing-docker
    docker:
      - image: hashicorp/terraform:0.12.26
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: ${aws_Administrator_access_key}
          aws-secret-access-key: ${aws_Administrator_secret_access_key}
          aws-region: ap-northeast-1  
      - run: terraform init
      - run: terraform plan

workflows:
  version: 2
  terraform plan:
    jobs:
      - terraform